spring:
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/hackathon-organizer/protocol/openid-connect/certs
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    vault:
      generic:
        enabled: true
        profile-separator: '/'
        default-context: messaging-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  application:
    name: messaging-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 0
ws:
  origins: ${WS.ORIGINS}


