spring:
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}
  cloud:
    vault:
      generic:
        enabled: true
        profile-separator: '/'
        default-context: messaging-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  application:
    name: messaging-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 0
ws:
  origins: ${WS_ORIGINS}


